"""OEI-009 step 2.6 — demo-falsifiable comparison data (idempotent, R1 rework).

TASK §0.3 carve-out: ONE allowed write into demo project id=1 (a restricted
classification comparison doc + explicit ACL row so demo_user sees it,
others don't).

R1 (codex VERDICT #2 §4.1): this script MUST be safely re-runnable so its
evidence files can be regenerated deterministically.

Rework history
--------------
v1 (a884d41 era) had two defects:
  (a) its cleanup DELETEd Onyx files **without the session cookie** and
      swallowed every exception with `except: pass` → every rerun left an
      orphan `ece-*-oei009-comparison-restricted` file behind, and the
      registry rows it deleted went out of sync with the engine. That is
      exactly how `05` ended up with `demo_user = 5`.
  (b) the file ids it deleted came ONLY from its own registry rows, so once
      a row was gone the Onyx file became unfindable.
  (c) it used a **time-based** marker, so every rerun produced a different
      controlled filename and a different recall behaviour → the evidence
      was not reproducible.

v2 (this file):
  (a) deletes carry the session cookie and record real status codes;
      any non-2xx is a LOUD failure, never swallowed.
  (b) files are additionally found **by name pattern** in project 1, so
      orphans without registry rows are still cleaned.
  (c) the marker is FIXED → deterministic controlled filename → the
      evidence can be regenerated byte-for-byte.
  (d) both demo queries are fixed and their recall composition is asserted.

Recall-composition root cause (measured 2026-09-25, this session)
-----------------------------------------------------------------
`POST /api/search` is NOT a plain vector top-k. It runs `SearchTool.run()`
(the same agentic multi-stage pipeline that powers chat mode — see
`/app/onyx/server/features/search/api.py` in the api_server container), which
includes LLM query expansion and LLM auto filter detection. Consequences,
all measured on this deployment:
  * latency 20–56 s per search;
  * the number of returned results is a *relevance* outcome, not a fixed k:
    the same corpus returned 1, 2, 3 or 4 docs for different queries;
  * therefore "which docs a query recalls" cannot be assumed — it is
    MEASURED here, and each chosen query is repeated to show stability.

Two queries, both verified stable (3/3 identical raw recall):

  DEMO_QUERY  = the marker token            → raw recall = 4
                (the 3 public demo docs + this restricted doc)
                ⇒ anonymous 3, other user 3, demo_user 4   [A4 / R1]

  ISO_QUERY   = 员工报销政策与发票审核流程  → raw recall = 1
                (ONLY this restricted doc — the topic exists nowhere else)
                ⇒ anonymous 0, other user 0, demo_user 1   [A7 no-hit / R2]

Using a *topically disjoint* section inside this doc (rather than a
meaningless random string) is what makes the zero-authorized-result branch a
genuine, explainable state instead of a retrieval accident.

Output: prints + JSON evidence (same shape as before, plus the R2 section).
"""
from __future__ import annotations

import datetime as dt
import json
import os
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

_REPO = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(_REPO / "ece" / "src"))

from sqlalchemy import text as _sql_text  # noqa: E402

from ece.db import get_engine  # noqa: E402


ONYX_BASE = os.environ.get("ECE_ONYX_BASE", "http://127.0.0.1:8080")
COOKIE_FILE = os.environ.get(
    "ECE_ONYX_COOKIE_FILE", "/home/fisher/.onyx-lab/.secrets/admin-cookies.txt"
)
PROJECT_ID = 1
DEMO_USER = "alice"
OTHER_USER = "bob"

# --- Fixed, deterministic identifiers (v1 used time-based → unreproducible) ---
MARKER = "oei009step26comparisonmarker"
DOCREF = "df16d19c9e7b"  # stable short ref for this demo doc's controlled name
CONTROLLED_FILENAME = f"ece-{DOCREF}-oei009-comparison-restricted.md"
ORIGINAL_FILENAME = "oei009-comparison-restricted.md"
SOURCE_SYSTEM_TAG = "system:oei009-step26"

# Demo ACL window length. A time box is the point (TASK §4 step 2.6 asks for a
# window, and step 3.3 demonstrates expiry/restore), but a 1-day box would
# silently expire the retained demo state while the cut is under review. 7 days
# keeps it bounded *and* durable; step33 restores to the same value.
ACL_VALID_DAYS = 7

# --- Fixed queries (each verified stable across repeats, see module docstring) ---
# A4/R1: recalls all 4 (3 public + this restricted) → 3 vs 4 across identities.
DEMO_QUERY = MARKER
# A7 no-hit / R2: recalls ONLY this restricted doc → 0 authorized results for
# anonymous, `engine_status` still "ok".
ISO_QUERY = "员工报销政策与发票审核流程"


def _load_cookies() -> dict[str, str]:
    jar: dict[str, str] = {}
    for raw in Path(COOKIE_FILE).read_text(encoding="utf-8", errors="replace").splitlines():
        line = raw.strip()
        if not line or (line.startswith("#") and not line.startswith("#HttpOnly_")):
            continue
        sep = "\t" if "\t" in line else None
        parts = line.split(sep) if sep else line.split()
        if len(parts) < 7:
            continue
        name = parts[5]
        value = "\t".join(parts[6:]) if sep == "\t" else " ".join(parts[6:])
        jar[name] = value
    return jar


def _http_json(method: str, path: str, *, body=None, headers=None) -> tuple[int, object]:
    url = f"{ONYX_BASE}{path}"
    data = None
    if body is not None:
        data = json.dumps(body).encode("utf-8")
    req = urllib.request.Request(url, method=method, data=data)
    req.add_header("Cookie", "; ".join(f"{k}={v}" for k, v in _load_cookies().items()))
    if body is not None:
        req.add_header("Content-Type", "application/json")
    if headers:
        for k, v in headers.items():
            req.add_header(k, v)
    try:
        with urllib.request.urlopen(req, timeout=120) as r:
            raw = r.read()
            try:
                return r.status, json.loads(raw) if raw else None
            except json.JSONDecodeError:
                return r.status, raw.decode("utf-8", errors="replace")
    except urllib.error.HTTPError as e:
        raw = e.read()
        try:
            return e.code, json.loads(raw) if raw else None
        except json.JSONDecodeError:
            return e.code, raw.decode("utf-8", errors="replace")


def _raw_recall(query: str) -> dict:
    """Direct engine recall composition for one query (evidence transparency).

    This is what the ECE filter is applied ON TOP OF. Recording it makes the
    mechanism auditable: the reviewer can see raw recall vs authorized set.

    `count` vs `distinct_titles` matters and is recorded deliberately: Onyx
    returns one entry PER CHUNK, so the same document can appear several
    times. The v1 evidence had `count=5` for 4 documents and that is exactly
    what made the first `05` look self-contradictory. The filter dedups by
    `engine_filename`, so the authorized set is what `distinct_titles` shows.
    """
    status, body = _http_json("POST", "/api/search", body={"query": query})
    results = (body or {}).get("results") or [] if isinstance(body, dict) else []
    titles = [r.get("title", "?") for r in results]
    return {
        "status": status,
        "count": len(results),
        "distinct_titles": sorted(set(titles)),
        "distinct_count": len(set(titles)),
        "titles": sorted(titles),
        "source_types": sorted({r.get("source_type", "?") for r in results}),
    }


def _wait_for_stale_clear(deadline_s: int = 240, interval_s: int = 20) -> tuple[list, bool]:
    """After cleanup, wait until the engine stops recalling our filename.

    Onyx deletes vectors ASYNCHRONOUSLY. Immediately after the two-step delete
    the old chunk can still be returned by /api/search, so a rerun would see
    its own previous artifact *alongside* the new one — the exact mechanism
    that produced the contradictory `05` in the first delivery. Waiting here
    makes the rerun's raw recall deterministic instead of timing-dependent.

    Returns (poll_history, cleared).
    """
    history: list = []
    start = time.monotonic()
    while time.monotonic() - start < deadline_s:
        status, body = _http_json("POST", "/api/search", body={"query": DEMO_QUERY})
        results = (body or {}).get("results") or [] if isinstance(body, dict) else []
        matches = sum(1 for r in results if r.get("title") == CONTROLLED_FILENAME)
        history.append(
            {"t": round(time.time(), 2), "status": status,
             "raw_count": len(results), "stale_matches": matches}
        )
        if matches == 0:
            return history, True
        time.sleep(interval_s)
    return history, False


def _cleanup_own_artifacts() -> dict:
    """R1: remove any artifacts created by THIS script's previous runs.

    Returns a small audit dict the script prints + saves.

    v1 defects fixed here (see module docstring):
      * DELETEs now carry the session cookie and record real status codes;
      * files are matched BY NAME PATTERN in project 1 as well as via registry
        rows, so orphans whose registry row is already gone are still found;
      * any non-2xx delete is a LOUD failure (never `except: pass`).
    """
    audit: dict = {
        "registry_deleted": 0,
        "acl_deleted": 0,
        "entity_deleted": 0,
        "files_deleted": [],
        "delete_failures": [],
        "files_found_by_name": [],
    }
    sql = get_engine()

    # 1. Find registry rows we own (engine_documents has no source_system
    #    column, so the script tags itself via uploaded_by).
    with sql.connect() as conn:
        reg_rows = conn.execute(
            _sql_text(
                """
                SELECT id, engine_document_id FROM engine_documents
                WHERE uploaded_by = :ub
                """
            ),
            {"ub": SOURCE_SYSTEM_TAG},
        ).fetchall()
    registry_ids = [int(r[0]) for r in reg_rows]
    eids = {str(r[1]) for r in reg_rows if r[1]}

    # 2/3. Delete ACL rows tied to our registry ids, then the registry rows.
    with sql.begin() as conn:
        for rid in registry_ids:
            n = conn.execute(
                _sql_text("DELETE FROM acl_entries WHERE object_ref = :o"),
                {"o": f"engine_document:{rid}"},
            ).rowcount
            audit["acl_deleted"] += n
        for rid in registry_ids:
            n = conn.execute(
                _sql_text("DELETE FROM engine_documents WHERE id = :i"),
                {"i": rid},
            ).rowcount
            audit["registry_deleted"] += n

    # 3b. ALSO find orphan files by name pattern in project 1 — covers files
    #     whose registry row is already gone (the v1 failure mode).
    status, listing = _http_json("GET", f"/api/user/projects/files/{PROJECT_ID}")
    if status == 200 and isinstance(listing, list):
        for f in listing:
            name = (f or {}).get("name") or ""
            fid = (f or {}).get("id") or ""
            if fid and name.startswith("ece-") and "oei009-comparison-restricted" in name:
                if str(fid) not in eids:
                    audit["files_found_by_name"].append(name)
                eids.add(str(fid))
    else:
        audit["delete_failures"].append(f"list project files -> {status}")

    # 4. Two-step delete Onyx files (DEMO-DATA-CLEANUP §2) — WITH cookies,
    #    recording real status codes; anything non-2xx is a loud failure.
    jar = "; ".join(f"{k}={v}" for k, v in _load_cookies().items())
    for eid in sorted(eids):
        ok = True
        for url in (
            f"{ONYX_BASE}/api/user/projects/{PROJECT_ID}/files/{eid}",  # 1) unlink -> 204
            f"{ONYX_BASE}/api/user/projects/file/{eid}",                # 2) delete -> 200
        ):
            req = urllib.request.Request(url, method="DELETE")
            req.add_header("Cookie", jar)
            try:
                with urllib.request.urlopen(req, timeout=20) as r:
                    code = r.status
            except urllib.error.HTTPError as e:
                code = e.code
            except Exception as e:  # network-level — loud, not silent
                audit["delete_failures"].append(f"{eid}: {type(e).__name__}: {e}")
                ok = False
                continue
            if code == 404:
                continue  # already gone
            if not (200 <= code < 300):
                audit["delete_failures"].append(f"{url} -> {code}")
                ok = False
        if ok:
            audit["files_deleted"].append(eid)

    return audit


def _body() -> bytes:
    """Fixed body → fixed embedding → reproducible recall composition.

    Two sections, deliberately:
      1. consulting-methodology band, so DEMO_QUERY (the marker) recalls this
         doc together with the 3 public demo docs;
      2. a topically disjoint internal-policy section, so ISO_QUERY recalls
         ONLY this doc (the only reachable zero-authorized-result state).
    """
    return (
        f"# OEI-009 受限对照文档 (restricted comparison doc)\n\n"
        f"marker: {MARKER}\n"
        f"controlled_filename: {CONTROLLED_FILENAME}\n\n"
        f"本文件用于 OEI-009 的“同一 query、两个身份 → 不同可见集合”可证伪演示。\n"
        f"它在 ECE 侧登记为 restricted，只有持有显式 allow ACL 行的用户可见。\n\n"
        f"## 主题对齐：咨询方法论\n\n"
        f"consulting methodology：问题树、假设驱动、MECE、销售交付衔接。\n"
        f"与 case-management-consulting、methodology-framework、\n"
        f"play-sales-delivery 三份演示文档同处一个主题带，因此以 marker 为\n"
        f"query 时可与之一起被召回，用于验证“同一 query、不同身份”的过滤。\n\n"
        f"## 内部受限内容：员工报销政策与发票审核流程\n\n"
        f"本段主题与咨询方法论无关，用于构造“零授权结果”分支：\n"
        f"员工报销需提交发票原件与审批单；单笔超过 5000 元需部门负责人二次审批；\n"
        f"发票审核关注抬头、税号与金额一致性；月度报销截止日为次月 5 日。\n"
    ).encode("utf-8")


def main() -> int:
    # R1 — clean up own artifacts FIRST (idempotency), and prove it happened.
    cleanup_audit = _cleanup_own_artifacts()
    print(f"== OEI-009 step 2.6 — cleanup: {json.dumps(cleanup_audit, ensure_ascii=False)}")

    today = dt.date.today()
    valid_to = today + dt.timedelta(days=ACL_VALID_DAYS)

    out: dict = {
        "marker": MARKER,
        "controlled_filename": CONTROLLED_FILENAME,
        "demo_query": DEMO_QUERY,
        "isolation_query": ISO_QUERY,
        "cleanup": cleanup_audit,
    }

    # R1: prove the cleanup actually took effect IN THE ENGINE, not just in the
    # DB. Onyx deletes vectors asynchronously, so without this wait a rerun
    # would recall its own previous artifact alongside the new one.
    if cleanup_audit["files_deleted"]:
        history, cleared = _wait_for_stale_clear()
        out["stale_clear"] = {"poll_history": history, "cleared": cleared}
        print(f"== stale-index clear: cleared={cleared} after {len(history)} poll(s)")
    else:
        out["stale_clear"] = {"poll_history": [], "cleared": True, "skipped": "nothing deleted"}

    # Upload via raw httpx (urllib doesn't support multipart as cleanly).
    import httpx  # local — script not on production path

    jar = httpx.Cookies()
    for n, v in _load_cookies().items():
        jar.set(n, v, domain="127.0.0.1", path="/")

    with httpx.Client(base_url=ONYX_BASE, cookies=jar, timeout=60.0) as cli:
        resp = cli.post(
            "/api/user/projects/file/upload",
            data={"project_id": str(PROJECT_ID)},
            files={"files": (CONTROLLED_FILENAME, _body(), "text/markdown")},
        )
        out["upload_status"] = resp.status_code
        out["upload_body"] = resp.json()
        if resp.status_code != 200:
            print(json.dumps(out, indent=2, default=str, ensure_ascii=False))
            return 1
        user_file_id = resp.json()["user_files"][0]["id"]
        out["user_file_id"] = user_file_id

        # Wait for indexing (poll with a hard cap, record every poll).
        deadline = time.monotonic() + 90
        indexed = False
        poll_history = []
        while time.monotonic() < deadline:
            poll = cli.post(
                "/api/user/projects/file/statuses",
                json={"file_ids": [user_file_id]},
            )
            poll_history.append(
                {"t": round(time.time(), 2), "status": poll.status_code, "body": poll.json()}
            )
            if poll.status_code == 200 and poll.json():
                rec = poll.json()[0]
                if rec.get("status") == "COMPLETED":
                    indexed = True
                    break
                if rec.get("status") == "FAILED":
                    print("FAILED indexing:", poll.json())
                    return 1
            time.sleep(2)
        out["poll_history"] = poll_history
        out["indexed"] = indexed
        if not indexed:
            print("indexing timed out")
            return 1

    # Register + ACL.
    sql_engine = get_engine()
    with sql_engine.begin() as conn:
        reg_row = conn.execute(
            _sql_text(
                """
                INSERT INTO engine_documents (
                    engine_name, engine_project_id, engine_filename, original_filename,
                    engine_document_id, title, classification, uploaded_by,
                    department, org_id
                )
                VALUES (
                    'onyx', :pid, :fname, :orig, :eid, :title, 'restricted',
                    :ub, '', NULL
                )
                ON CONFLICT (engine_name, engine_filename) DO UPDATE
                  SET engine_document_id = EXCLUDED.engine_document_id,
                      classification     = 'restricted'
                RETURNING id
                """
            ),
            {
                "pid": PROJECT_ID,
                "fname": CONTROLLED_FILENAME,
                "orig": ORIGINAL_FILENAME,
                "eid": user_file_id,
                "title": "OEI-009 step 2.6 restricted comparison",
                "ub": SOURCE_SYSTEM_TAG,
            },
        ).first()
        registry_id = int(reg_row[0])
    object_ref = f"engine_document:{registry_id}"

    with sql_engine.begin() as conn:
        conn.execute(
            _sql_text(
                "INSERT INTO entities (entity_type, name, normalized_name, source_system, source_id, attributes) "
                "VALUES ('person', 'OEI-009 Demo User', 'oei-009 demo user', :ss, :sid, "
                "jsonb_build_object('department', 'demo', 'roles', '[\"demo_user\"]'::jsonb, 'is_management', false)) "
                "ON CONFLICT (entity_type, source_system, source_id) DO NOTHING"
            ),
            {"ss": SOURCE_SYSTEM_TAG, "sid": DEMO_USER},
        )
        conn.execute(
            _sql_text("DELETE FROM acl_entries WHERE object_ref = :oref"),
            {"oref": object_ref},
        )
        conn.execute(
            _sql_text(
                """
                INSERT INTO acl_entries
                    (subject_type, subject_ref, object_type, object_ref, effect,
                     valid_from, valid_to, source_system, note)
                VALUES
                    ('user', :sub, 'engine_document', :oref, 'allow',
                     :vf, :vt, :ss, 'OEI-009 step 2.6 demo ACL')
                """
            ),
            {
                "sub": DEMO_USER,
                "oref": object_ref,
                "vf": today,
                "vt": valid_to,
                "ss": SOURCE_SYSTEM_TAG,
            },
        )

    out["registry_id"] = registry_id
    out["acl"] = {
        "subject_ref": DEMO_USER,
        "object_ref": object_ref,
        "valid_from": today.isoformat(),
        "valid_to": valid_to.isoformat(),
        "valid_days": ACL_VALID_DAYS,
    }

    # Raw engine recall composition — makes the filter's input auditable.
    out["raw_recall"] = {
        "demo_query": _raw_recall(DEMO_QUERY),
        "isolation_query": _raw_recall(ISO_QUERY),
    }

    # Probe /library with three identities, for BOTH queries.
    os.environ["ECE_CONTENT_ENGINE"] = "onyx"
    os.environ.setdefault("DATABASE_URL", str(sql_engine.url))
    for mod in list(sys.modules):
        if mod.startswith("ece."):
            del sys.modules[mod]
    from fastapi.testclient import TestClient  # noqa: PLC0415
    from ece.main import app  # noqa: PLC0415

    client = TestClient(app)
    identities = (
        ("anonymous", {}),
        ("demo_user", {"X-User-Id": DEMO_USER}),
        ("other_user", {"X-User-Id": OTHER_USER}),
    )
    for qname, query in (("demo", DEMO_QUERY), ("isolation", ISO_QUERY)):
        for label, headers in identities:
            r = client.get(
                "/api/v1/consulting/library",
                params={"q": query},
                headers=headers,
            )
            payload = r.json()
            titles = [it["title"] for it in payload.get("engine_items", [])]
            out[f"{qname}__{label}"] = {
                "query": query,
                "status": r.status_code,
                "engine_status": payload.get("engine_status"),
                "engine_items_count": len(titles),
                "engine_items_titles": sorted(titles),
                "restricted_visible": CONTROLLED_FILENAME in titles,
            }

    print(json.dumps(out, indent=2, default=str, ensure_ascii=False))

    # ---- Assertions -------------------------------------------------------
    fail = False
    print()
    for qname in ("demo", "isolation"):
        for label in ("anonymous", "demo_user", "other_user"):
            s = out[f"{qname}__{label}"]
            print(
                f"{qname:9s} {label:10s}: {s['engine_items_count']} items "
                f"(engine_status={s['engine_status']}, restricted={s['restricted_visible']})"
            )

    expect = {
        # A4 / R1 — same query, two identities → different authorized sets.
        ("demo", "anonymous"): 3,
        ("demo", "other_user"): 3,
        ("demo", "demo_user"): 4,
        # A7 no-hit / R2 — the only reachable zero-authorized-result state.
        ("isolation", "anonymous"): 0,
        ("isolation", "other_user"): 0,
        ("isolation", "demo_user"): 1,
    }
    for key, want in expect.items():
        got = out[f"{key[0]}__{key[1]}"]["engine_items_count"]
        if got != want:
            print(f"FAIL — {key[0]}__{key[1]} expected {want}, got {got}")
            fail = True

    # Raw recall must contain our doc exactly ONCE — i.e. no stale chunk from a
    # previous run is still being returned (R1 reproducibility).
    n_self = out["raw_recall"]["demo_query"]["titles"].count(CONTROLLED_FILENAME)
    if n_self != 1:
        print(f"FAIL — raw recall contains {n_self} entries for the controlled filename (expected 1)")
        fail = True

    # The restricted doc must be invisible to anyone without the ACL row, in
    # BOTH queries — and its title must not appear at all (no side channel).
    for label in ("anonymous", "other_user"):
        for qname in ("demo", "isolation"):
            if out[f"{qname}__{label}"]["restricted_visible"]:
                print(f"FAIL — restricted doc visible to {label} on {qname}")
                fail = True
    if out["demo__anonymous"]["engine_status"] != "ok":
        print("FAIL — demo/anonymous engine_status != ok")
        fail = True
    if out["isolation__anonymous"]["engine_status"] != "ok":
        print("FAIL — isolation/anonymous engine_status != ok (must be ok, not unavailable)")
        fail = True

    if fail:
        return 1
    print()
    print(
        "PASS — Step 2.6 (R1): demo_query → anon/other 3, demo_user 4 "
        "(restricted hidden from non-holders); isolation_query → anon/other 0 "
        "(engine_status=ok, genuine zero-authorized-result), demo_user 1."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
